spring.application.name=backendd


# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=${MONGO_URI}

# JWT Secret Key (placeholder, will add in security later)

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000   # 1 day in ms

#spring.security.enabled=false
#spring.security.basic.enabled=false